kind: Pod
metadata:
  labels:
    dask_type: scheduler
spec:
  restartPolicy: Never
  containers:
    - image: gcr.io/[YOUR_PROJECT_PATH]/dask-unified:0.18
      imagePullPolicy: IfNotPresent
      args: [ dask-scheduler ]
      name: dask-scheduler
      resources:
        limits:
          cpu: "3"
          memory: 10G
          nvidia.com/gpu: 1
        requests:
          cpu: "3"
          memory: 10G