kind: Pod
metadata:
  labels:
    dask_type: scheduler
spec:
  restartPolicy: Never
  containers:
    - image: gcr.io/[YOUR_GCP_PROJECT]/[YOUR_USER_ID]/dask-unified:0.19
      imagePullPolicy: IfNotPresent
      args: [ dask-scheduler ]
      name: dask-scheduler
      resources:
        limits:
          cpu: "10"
          memory: 80G
          nvidia.com/gpu: 1
        requests:
          cpu: "10"
          memory: 80G