kind: Pod
metadata:
  labels:
    dask_type: "worker"
spec:
  restartPolicy: Never
  volumes:
    - name: gcsfs-creds
      secret:
        secretName: gcsfs-creds
        items:
          - key: keyfile.json
            path: keyfile.json
  tolerations:
    - key: "daskrole"
      operator: "Equal"
      value: "worker"
      effect: "NoSchedule"
  containers:
    - image: gcr.io/[YOUR_GCP_PROJECT]/[YOUR_USER_ID]/dask-unified:0.18
      imagePullPolicy: IfNotPresent
      args: [ dask-cuda-worker, $(DASK_SCHEDULER_ADDRESS), --rmm-managed-memory ]
      name: dask-cuda-worker
      resources:
        limits:
          cpu: "7"
          memory: 25G
          nvidia.com/gpu: 1
        requests:
          cpu: "7"
          memory: 25G
      ## Uncomment for XGBoost with custom mortgage data
      #volumeMounts:
      #  - name: gcsfs-creds
      #    mountPath: "/etc/secrets"
      #    readOnly: true
      #env:
      #  - name: GOOGLE_APPLICATION_CREDENTIALS
      #    value: "/etc/secrets/keyfile.json"