kind: Pod
metadata:
    labels:
        dask_type: GPU_worker
spec:
    restartPolicy: Never
    containers:
      - image: rapidsai/rapidsai-nightly:cuda11.0-runtime-ubuntu18.04-py3.8
        imagePullPolicy: IfNotPresent
        args: [dask-cuda-worker, $(DASK_SCHEDULER_ADDRESS), --rmm-pool-size, 10GB]
        name: dask-cuda-worker
        resources:
          limits:
            cpu: "2"
            memory: 6G
            nvidia.com/gpu: 1
          requests:
            cpu: "2"
            memory: 6G